import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.scss";
import 'bootstrap/dist/css/bootstrap.min.css';
const inter = Inter({ subsets: ["latin"] });
import { Provider } from 'react-redux'
import { store } from "../../lib/store";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params : {
    locale
  
  }
}: Readonly<{
  children: React.ReactNode;
  params : {
    locale : string
  }
}>) {
  return (   
    <html lang={locale}>
      <body  >
     
        {children}
        
        
        </body>
    </html>
  );
}
